name: minimal
description: Minimal theme for Martini.
version: 1.0.0
homepage: https://jaguar-dart.github.io/
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_martini: # ^1.4.1
    path: ../jaguar_martini
  stencil:
  date_format: ^1.0.4
  jaguar_hotreload: ^0.2.3

dev_dependencies:
  test: ^0.12.0
